# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false
notifications:
  email:
    - stefanie.schneider@itg.uni-muenchen.de

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  - bash <(curl -s https://codecov.io/bash)
